class Config():
    DEBUG=False
    SQL_ALCHEMY_TRACK_NOTIFICATION=False

class LocalDevelopementConfig(Config):
    DEBUG=True
    SQLALCHEMY_DATABASE_URI='sqlite:///database.sqlite3'
    SECURITY_PASSWORD_HASH='bcrypt'
    SECURITY_PASSWORD_SALT='ADDSALTTOAPPLICATION'
    SECRET_KEY='APPLICATION'
    SECURITY_TOKEN_AUTHENTICATION_HEADER='Access-Token'
    WTF_CSRF_ENABLED=False

